services:
  postgres:
    container_name: parking-postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: parking
    ports:
        - 5432:5432